apiVersion: v1
kind: Pod
metadata:
  name: pod-no-toleration
  namespace: taint-toleration-demo
  labels:
    app: taint-demo
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
  tolerations:
  - key: "maintenance"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
